---

- name: Copy all apps to /usr/bin
  copy:
    src: "files/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    mode: u=rx,g=rx,o=rx
  with_items: "{{ binary_apps }}"

#- name: Install httpie
#  raw: "pip install --upgrade pip setuptools && pip install --upgrade httpie"
