---

ansible_distribution: "{{ lookup('env','ANSIBLE_DISTRIBUTION') }}"

binary_apps:
  - consul-template
  - direnv
  - envconsul
  - hoverctl
  - hoverfly
  - jj
  - jq
  - bat
  - mitmdump
  - mitmproxy
  - mitmweb
  - rg
  - jless
  - fd
  - gum
#  - venv
#  - wrk
