---

- name: Install build deps Debian
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ erlang_build_debian_deps }}"
  when:
    - ansible_distribution | lower == "debian"

- name: Install build deps CentOS
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ erlang_build_centos_deps }}"
  when:
    - ansible_distribution | lower == "centos"

- name: Creating directory for Kerl tool
  file:
    path: "{{ kerl_working_dir }}"
    state: directory

- name: Downloading Kerl tool
  get_url:
    url: "{{ kerl_download_url }}"
    dest: "{{ kerl_working_dir }}/kerl"

- name: Getting exec permissions to Kerl tool
  raw: "chmod a+x {{ kerl_working_dir }}/kerl"

- name: Building Erlang
  raw: "{{ kerl_working_dir }}/kerl build {{ erlang_version }} {{ erlang_version }}"

- name: Installing Erlang
  raw: "{{ kerl_working_dir }}/kerl install {{ erlang_version }} {{ kerl_working_dir }}/{{ erlang_version }}"

# ALERT: paths with numbers fixed!
- name: setcap CAP_NET_BIND_SERVICE=+eip
  raw: "setcap CAP_NET_BIND_SERVICE=+eip /home/app/22.2/erts-10.6/bin/beam.smp"
