---

- name: Provision Python
  hosts: all
  gather_facts: no
  tasks:
    - name: Boostrap python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: Provision Spark 2.x
  hosts: all

  tasks:
#    - name: "Creates directory: /etc/services.d/worker"
#      file:
#        path: /etc/services.d/worker
#        state: directory
#
#    - name: Putting /etc/services.d/worker/run
#      copy:
#        src: files/services.d/worker/run
#        dest: /etc/services.d/worker/run
#        owner: root
#        group: root
#        mode: u=rx,g=rx,o=rx

    - name: Putting /usr/local/spark/bin/worker.sh
      copy:
        src: files/worker.sh
        dest: /usr/local/spark/bin/worker.sh
        owner: root
        group: root
        mode: u=rx,g=rx,o=rx
