
- name: Create protoc dir
  file:
    path: /usr/lib/protoc
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Putting protoc-chain
  unarchive:
    src: https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip
    dest: /usr/lib/protoc
    remote_src: yes
    validate_certs: no
