---

- name: Provision Python
  hosts: all
  gather_facts: no
  tasks:
    - name: Boostrap Python
      raw: apt-get -y update && apt-get install -y python3-minimal

- name: Provision Java
  hosts: all

  tasks:

    - name: Include task for install Java 8
      include_tasks: "../tasks/install-corretto-jdk8.yaml"

