---

- name: Provision Python
  hosts: all
  gather_facts: no
  tasks:
    - name: Boostrap python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: Provision Test app
  hosts: all

  tasks:
    - name: "Creates directory: /etc/services.d/service-a"
      file:
        path: /etc/services.d/service-a
        state: directory

    - name: Putting /etc/services.d/service-a/run
      copy:
        src: files/services.d/service-a/run
        dest: /etc/services.d/service-a/run
        owner: root
        group: root
        mode: u=rx,g=rx,o=rx

    - name: Putting /home/app/service-a.sh
      copy:
        src: files/service-a.sh
        dest: /home/app/service-a.sh
        owner: root
        group: root
        mode: u=rx,g=rx,o=rx

    - name: Putting service-a
      copy:
        src: files/service-a
        dest: /home/app/service-a
        mode: u=rx,g=rx,o=rx


