---

python_versions1:
  - { d: 3.3.7, b: 3.3 }
  - { d: 3.4.10, b: 3.4 }
  - { d: 3.5.10, b: 3.5 }
  - { d: 3.6.15, b: 3.6 }

python_versions2:
  - { d: 3.7.15, b: 3.7 }
#  - { d: 3.8.15, b: 3.8 }
  - { d: 3.9.15, b: 3.9 }
  - { d: 3.10.8, b: 3.10 }
  - { d: 3.11.0, b: 3.11 }

python_build_debian_deps:
  - build-essential
#  - checkinstall
#  - libreadline-gplv2-dev
  - libreadline-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libdb5.3-dev
  - libexpat1-dev
  - liblzma-dev
  - libffi-dev
  - libc6-dev
  - libbz2-dev
  - uuid-dev
  - zlib1g-dev
  - openssl
  - python3
  - python3-dev
  - python3-setuptools
#  - python3.10-venv
  - python3-doc
  - python3-venv
  - python3-pip
  - binutils
  - binfmt-support
  - readline-doc
  - wget
  - gcc-9
  - gfortran
  - libopenblas-dev
  - liblapack-dev
  - libsm6
  - libxext6


python_build_centos_deps:
  - python3-setuptools
  - wget
  - openssl-devel
  - bzip2-devel
  - libffi-devel
