---

- name: Install deps Debian
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ debian_deps }}"
  when:
    - ansible_distribution | lower == "debian"

- name: Install deps CentOS
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ centos_deps }}"
  when:
    - ansible_distribution | lower == "centos"
