---
- name: Install deps
  import_tasks: deps.yml

- name: Putting s6-overlay noarch
  ansible.builtin.unarchive:
    src: files/s6-overlay-noarch-v3.1.5.0.tar.xz
    dest: /

- name: Putting s6-overlay
  ansible.builtin.unarchive:
    src: files/s6-overlay-x86_64-v3.1.5.0.tar.xz
    dest: /

#- name: Putting symlinks noarch
#  ansible.builtin.unarchive:
#    src: files/s6-overlay-symlinks-noarch.tar.xz
#    dest: /
#
#- name: Putting symlinks arch
#  ansible.builtin.unarchive:
#    src: files/s6-overlay-symlinks-arch.tar.xz
#    dest: /
#
#- name: Putting syslogd overlay noarch
#  ansible.builtin.unarchive:
#    src: files/syslogd-overlay-noarch.tar.xz
#    dest: /

#- name: ssh 1
#  raw: echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
#  when:
#    - ansible_distribution | lower == "centos"
#

- name: "Creates directory: /etc/s6-overlay/s6-rc.d/user/contents.d"
  file:
    path: /etc/s6-overlay/s6-rc.d/user/contents.d
    state: directory

- name: Create app group
  group:
    name: app
    state: present

- name: Create user
  user:
    name: app
    state: present
    group: app
    shell: /bin/bash
    groups:
      - app
      - staff
      - sudo

#- name: key-gen 1
#  raw: /usr/bin/ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -C '' -N ''
#  when:
#    - ansible_distribution | lower == "centos"
#
#- name: key-gen 2
#  raw: /usr/bin/ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''
#  when:
#    - ansible_distribution | lower == "centos"
#
#- name: key-gen 3
#  raw: /usr/bin/ssh-keygen -q -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -C '' -N ''
#  when:
#    - ansible_distribution | lower == "centos"
