---

- name: Insert a line at the end of a file
  lineinfile:
    path: /home/app/.bashrc
    line: 'eval "$(direnv hook bash)"'

- name: Insert a line at the end of a file
  lineinfile:
    path: /home/app/.bashrc
    line: 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib'

- name: Install apps
  import_tasks: install.yml
