#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  gather_facts: false
  vars:
    src_path: "{{ lookup('env','SRC_PATH') }}"
    ssh_path: "{{ lookup('env','SSH_PATH') }}"

  tasks:
    - name: Create container
      docker_container:
        name: ansible-based-compiler
#        image: "jalbert/elixir:19-ubuntu18"
#        image: "jalbert/elixir:19-debian10"
        image: "jalbert/elixir:19-centos7"
        detach: true
        interactive: true
        tty: true
        debug: yes
        volumes:
          - "{{ src_path }}:/home/app/src"
          - "{{ ssh_path }}:/home/app/.ssh"

    - name: Add docker container to inventory
      add_host:
        name: ansible-based-compiler
        ansible_connection: docker
        ansible_user: app

- hosts: ansible-based-compiler
  gather_facts: false
  vars:
    user_id: "{{ lookup('env','USER_ID') }}"
    group_id:  "{{ lookup('env','GROUP_ID') }}"
    utility_scripts:
      - release_command.sh

  tasks:
    - name: Putting scripts
      copy:
        src: "bin/{{ item }}"
        dest: "/home/app/src/bin/{{ item }}"
        owner: app
        group: app
        mode: u+x
      with_items: "{{ utility_scripts }}"

#    - name: Set release version
#      lineinfile:
#        path: /home/app/src/mix.exs
#        regexp: '(^\s*)version: (\".+)\"'
#        line: >
#          \1version: \2-{{ os_name.stdout | trim() }}-{{ suffix.stdout | trim() }}",
#        backrefs: yes

    - name: Compile project
      raw: /home/app/entrypoint.sh

    - name: Target git revision
      raw: git rev-parse --verify HEAD | cut -c1-6
      register: suffix

    - name: Target version
      raw: >
        sed -nr 's/(^\s*)version: "(.+)(",)/\2/p' /home/app/src/mix.exs
      register: version

    - name: Target OS
      # xargs is for removing leading/trailing spaces
      raw: cat /etc/os-release | grep ^PRETTY | cut -c13-50 | tr '"/()' ' ' | xargs | tr ' ' '-'
      register: os_name

    - name: Target Project name
      raw: ls _build/prod/rel
      register: build_outputs

    - name: Create tar file
      raw: "tar -cf {{ build_outputs.stdout_lines[0] }}-{{ version.stdout | trim() }}-{{ os_name.stdout | trim() }}-{{ suffix.stdout | trim() }}.tar -C _build/prod/rel {{ build_outputs.stdout_lines[0] }}"

    - name: Removing scripts
      file:
        path: "/home/app/src/bin/{{ item }}"
        state: absent
      with_items: "{{ utility_scripts }}"

- hosts: localhost
  gather_facts: false

  tasks:
    - name: destroy container
      docker_container:
        name: ansible-based-compiler
        state: absent
