---

- name: Provision Python
  hosts: all
  gather_facts: no
  vars:
    ansible_distribution: "{{ lookup('env','ANSIBLE_DISTRIBUTION') }}"

  tasks:

    - name: Boostrap Python Debian
      raw: apt-get -y update && apt-get install -y python-minimal
      when:
        - ansible_distribution | lower == "debian"

    # https://stackoverflow.com/questions/32407164/the-vm-is-running-with-native-name-encoding-of-latin1-which-may-cause-elixir-to/43522172
    - name: Fixing locales in Ubuntu
      raw: apt-get update && apt-get install -y --no-install-recommends locales && LANG=en_US.UTF-8 && echo $LANG UTF-8 > /etc/locale.gen && locale-gen && update-locale LANG=$LANG
      when:
        - ansible_distribution | lower == "debian"

    - name: Boostrap Python CentOS
      raw: yum -y install epel-release && yum -y update
      when:
        - ansible_distribution | lower == "centos"

- name: Provision s6-ssh
  hosts: all

  tasks:
    - name: s6-based server
      include_role:
        name: s6-server
      vars:
        ansible_distribution: "{{ lookup('env','ANSIBLE_DISTRIBUTION') }}"

    - name: To provide utilities
      include_role:
        name: utilities
      vars:
        ansible_distribution: "{{ lookup('env','ANSIBLE_DISTRIBUTION') }}"
