---

- name: Provision Python
  hosts: all
  gather_facts: no
  tasks:
    - name: Boostrap python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: Provision Java
  hosts: all

  tasks:
    - name: Create workdir
      file:
        path: /usr/lib/jvm
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Putting JDK
      copy:
        src: files/jdk-11.0.6_linux-x64_bin.tar.gz
        dest: /usr/lib/jvm/jdk.tar.gz
        owner: root
        group: root

    - name: Unpacking
      raw: tar -xzf /usr/lib/jvm/jdk.tar.gz -C /usr/lib/jvm/

    - name: Remove jdk file
      raw: rm -rf /usr/lib/jvm/jdk.tar.gz

    - name: update-alternatives java
      raw: update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk-11.0.6/bin/java" 1

    - name: update-alternatives javac
      raw: update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk-11.0.6/bin/javac" 1

    - name: setting JAVA_HOME
      raw: echo 'JAVA_HOME=/usr/lib/jvm/jdk-11.0.6' >> /etc/environment

    - name: setting JAVA_HOME
      raw: echo 'export JAVA_HOME=/usr/lib/jvm/jdk-11.0.6' > /etc/profile.d/custom_inits.sh

    - name: setting JAVA_HOME/bin
      raw: echo 'export PATH="$PATH:$JAVA_HOME/bin"' >> /etc/profile.d/custom_inits.sh

