---

- name: Install Elixir
  import_tasks: install.yml

- name: Putting entrypoint
  template:
    src: templates/entrypoint.sh.j2
    dest: /home/app/entrypoint.sh
    owner: app
    group: app
    mode: u=rx,g=rx,o=rx

- name: Putting update_user_ids.sh
  template:
    src: files/update_user_ids.sh
    dest: /usr/bin/update_user_ids.sh
    owner: app
    group: app
    mode: u=rxw,g=rxw,o=rxw

- name: Insert a line at the end of a file
  lineinfile:
    path: /home/app/.bashrc
    line: ". {{ kerl_working_dir }}/{{ erlang_version }}/activate"

- name: Insert a line at the end of a file
  lineinfile:
    path: /home/app/.bashrc
    line: "export PATH=\"$PATH:{{ elixir_bin_dir }}/bin\""

#- name: Insert a line at the end of a file
#  lineinfile:
#    path: /home/app/.bashrc
#    line: "mix local.rebar --force && mix local.hex --force"

- name: Insert a line at the end of a file
  lineinfile:
    path: /home/app/.bashrc
    line: "envconsul -consul-addr=172.17.0.2:8500 -prefix nomad- /usr/bin/update_user_ids.sh"

- name: Insert a line at the end of a file
  lineinfile:
    path: /home/app/.bashrc
    line: "export SECRET_KEY_BASE={{ secret_key_base }}"

#- name: Putting envconsul
#  copy:
#    src: files/envconsul
#    dest: /home/app/envconsul
#    owner: app
#    group: app
#    mode: u=rx,g=rx,o=rx


#- name: set CAP_SYS_ADMIN to /usr/local/bin/update_user_ids.sh
#  raw: setcap CAP_SYS_ADMIN=+eip /usr/local/bin/update_user_ids.sh

#- name: Cleanup
#  import_tasks: cleanup.yml
