---

- name: Install Elixir
  import_tasks: install.yml

- name: Putting entrypoint
  template:
    src: templates/entrypoint.sh.j2
    dest: /home/app/entrypoint.sh
    owner: app
    group: app
    mode: u=rx,g=rx,o=rx

- name: Putting update_user_ids.sh
  template:
    src: files/update_user_ids.centos
    dest: /home/app/update_user_ids.sh
    owner: app
    group: app
    mode: u=rx,g=rx,o=rx

- name: Putting envconsul
  copy:
    src: files/envconsul
    dest: /home/app/envconsul
    owner: app
    group: app
    mode: u=rx,g=rx,o=rx


#- name: set CAP_SYS_ADMIN to /usr/local/bin/update_user_ids.sh
#  raw: setcap CAP_SYS_ADMIN=+eip /usr/local/bin/update_user_ids.sh

#- name: Cleanup
#  import_tasks: cleanup.yml
